### ISSUE TITLE
[0.5.1] VSCode debug adapter hangs on sync in case the app fails to run

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#105]
If the app fails to run on sync operation the debug adapter process hangs and can't be disconnected even by pressing the disconnect button (the red square).

**Comment by hshristov** [comment]
+1

**Comment by ivanbuhov** [comment]
Fixed https://github.com/NativeScript/nativescript-vscode-extension/commit/c7f06e3a055c21cc45029cdd5ce3d1a3be0acc34
