### ISSUE TITLE
create automated build that creates a vsix packge

### ISSUE THREAD

**Issue by blagoev** [NativeScript/nativescript-vscode-extension#11]
@ErjanGavalji: Erji can you please help us with that

**Comment by ivanbuhov** [comment]
* [ ] Set up a build job
* [ ] Run tests as part of the build process

**Comment by ivanovit** [comment]
Hi,

The automated build has been implemented and integrated. Now we have travis to run tests and tslint on each pull request. Also, we have 2 internal jobs for building and publishing the extension to the gallery.
