### ISSUE TITLE
Variables are no longer displayed when debugging in VS Code 1.9.0 and {N} plugin 0.6.x

### ISSUE THREAD

**Issue by DavyDeDurpel** [NativeScript/nativescript-vscode-extension#112]
Watches and Evaluation still works, but the Variables view is empty and when hovering over a variable the popup does not appear.

**Comment by ivanbuhov** [comment]
Related to https://github.com/NativeScript/nativescript-vscode-extension/issues/21

**Comment by Pip3r4o** [comment]
@DavyDeDurpel https://github.com/NativeScript/nativescript-vscode-extension/issues/21#issuecomment-281364660

**Comment by ivanbuhov** [comment]
@Pip3r4o Since [this PR](https://github.com/NativeScript/android-runtime/pull/714) is merged can I close this issue?
