### ISSUE TITLE
Debugging is not compatible with TypeScript Hero VS Code extension

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#114]
Steps to reproduce:
1. Install and enable [TypeScript Hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero) VS Code extension.
2. Run `Launch on iOS/Android` debug command.
3. Change a file and save it (`Ctrl+S`) to trigger a sync.
The expected behaviour is to sync successfully and reattach the VS Code debugger.
The actual result is app is synced but after reattaching, a restart (disconnect({restart: true})) event is triggered by the `TypeScript Hero` plugin and debug adapter processes restarted. Then another restart event is triggered and the process of starting and stopping the debug adapter continues infinitely repeated.

**Comment by ivanovit** [comment]
I am closing this issue because the problem should no longer exist. The debugger restart options has been removed from TypeScript here - https://github.com/buehler/typescript-hero/pull/191/commits/235e088ea8492bdbed8b153134c50727afa84fec
