### ISSUE TITLE
Android debugger does not work

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#119]
_From @mannouman on February 9, 2017 14:32_

Hi,

When i launch the debugger (Android launch or Android attach on my device) in Visual Studio Code, the debugger seems to connect but quit immediately, see the trace below : 

```
# NativeScript Debugger started #
[NSDebugAdapter] Ready to attach to application on 40000
[NSDebugAdapter] Connection to target application established on 40000
Error: Unknown signal: SIGQUIT
```

Any idea ?
Thanks

_Copied from original issue: NativeScript/nativescript-cli#2520_

**Comment by ivanbuhov** [comment]
_From @halaharr on February 9, 2017 15:44_

This worked after I did this.
"you could try to delete launch.json file from .vscode folder in your project and to generate it again while following the instructions [here](https://docs.nativescript.org/tooling/visual-studio-code-extension#generate-launch-configurations)."

**Comment by ivanbuhov** [comment]
_From @mannouman on February 9, 2017 16:43_

Thanks Halaharr, the debugger is well connected now. 

But i don't understand it does not stop on my breakpoints...

if it helps, see my launch.json configuration (android part) : 

```
{
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true,
            "stopOnEntry": false
        },
        {
            "name": "Attach on Android",
            "type": "nativescript",
            "request": "attach",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        }
```

**Comment by ivanbuhov** [comment]
_From @halaharr on February 9, 2017 16:47_

I have seen that happen before. It takes some time sometime for the breakpoints to be enabled.  Here is my launch.json settings
 {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        },

**Comment by ivanbuhov** [comment]
@halaharr From v2.5 only inline source maps are supported on Android. If you are debugging TypeScript project, make sure the generated `.js` files have source maps inlined.

**Comment by ivanbuhov** [comment]
_From @mannouman on February 9, 2017 17:30_

@halaharr i tried with the same conf as yours but same problem.

I will retry with another device but with this one (Oneplus 3) i can debug Android native in android studio so i don't think the problem comes from my device.

@ivanbuhov i am not using TypeScript

Thanks for your help guys ! any ather idea ?

**Comment by ivanbuhov** [comment]
_From @fbeaulieu on February 28, 2017 1:39_

Nativescript (vanilla javascript)
VSCode 191
nativescript extension 061

Same problem here, from VSCODE 191, variable section is foreever empty. Breakpoints works but after application is launched. Nativescript pre-launch events do not hit at all now. Watch section works well though. Tried all possible combination of launch.json (destroyed it, recreate vanilla, said a prayer...)

Just wondering if it's an extension bug or a vscode bug (which I think it is...)

any help is welcomed !

**Comment by scavezze** [comment]
@ivanbuhov you ever get this working I am currently stuck with 

> [NativeScriptCli] execute: tns --version
> [NSDebugAdapter] Using tns CLI v2.5.3 on path 'tns'
> [NSDebugAdapter] Running tns command...
> [NativeScriptCli] execute: tns debug android --no-client --start 
> [NSDebugAdapter] Watching the tns CLI output to receive a connection token
> device: 0815f8fbdaed1a04 debug port: 40000
> [NSDebugAdapter] Ready to attach to application on 40000
> [NSDebugAdapter] Connection to target application established on 40000
> Error: Unknown signal: SIGQUIT

**Comment by pkoleva** [comment]
Hey @scavezze,

We had a similar problem but it was caused by the CLI. Could you update to 2.5.5 or 3.0.1 and check if it still happens?

Thanks!

**Comment by MrFoxPro** [comment]
@scavezze you can try start it from command prompt, not from debug panel ([like this](https://docs.nativescript.org/img/visual-studio-code-extension/nativescript-commands.png)) and attach debugger. Works for me.

**Comment by rolaru** [comment]
Hello guys,

I'm using NativeScript 3.3.0 and also have issues with debugging a NS Core app. My breakpoints don't work in neither VS Code nor running "tns debug android". I tried all the advice from above and still didn't manage to make it work. Below is my Android launch.json configuration. Any ideas?

    {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        }

**Comment by Pip3r4o** [comment]
@rolaru are you perhaps setting your breakpoints too early during code execution (entry file?) If that's the case, then you should place `debugger` statements at the key points where need to break, and initiate the debugging session with the `--debug-brk` flag, as explained in the following article: https://docs.nativescript.org/tooling/chrome-devtools#debugger

**Comment by rolaru** [comment]
@Pip3r4o, it does indeed work this way and it's great. But isn't there a possibility that we can put a breakpoint in Visual Studio first and afterwards run the debugger so that it knows where to stop?

**Comment by Pip3r4o** [comment]
@rolaru the debug inspector works on the main thread, where most of your javascript, and the one that you'll be debugging, executes. The `--debug-brk` is necessary to instruct the runtime(platform) to not run any code before the debugger has attached, so as to not execute a script before having a chance to work with the debugger. 

It is possible that the script is parsed and executed first, before notifications of 'preset' breakpoints are sent to the inspector, however `debugger` statements are part of your code execution, so if your inspector is connected, it will most certainly pause.

The limitation is expected, and I consider the debugger to be working `as intended`, if a bit `unexpected` for first-time users of chrome devtools and the visual studio code debugger. Now, we could workaround that behavior, but it certainly won't be clean, so I recommend using `debugger` + `--debug-brk` when debugging startup code.

**Comment by rolaru** [comment]
I understand. Thanks a lot! Greatly appreciated!
