### ISSUE TITLE
Inspector session not disconnected when disconnecting debug adapter

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-vscode-extension#123]
### Problem:
Once the VSCode debugger is attached to a NS application, it doesn't disconnect properly afterwards - breakpoints will be left intact, and apps will pause, when in fact a debugger isn't visibly connected.

### Steps to reproduce:
- open any app in VSC
- set breakpoints in tap handler
- Launch Android
- tap to verify debugger breaks
- continue execution
- stop debugging session
- tap button -> application breaks - it should instead execute without pausing

**Comment by ivanovit** [comment]
I am closing this issue because the problem should no longer exist in the latest version. 
Please, do not hesitate to reopen it if you continue to experience the issue.
