### ISSUE TITLE
Variables empty when debugging Android app

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-vscode-extension#131]
On iOS when hit a breakpoint variables can be inspected either by hovering over or in the Variables tab on the left. This is not the case for Android: hovering over a variable does nothing and the tab is empty.

My config:
Visual Studio 1.11.2 
NativeScript support for VS Code 0.6.1
nativescript 2.5.4
tns-core-modules 2.5.2
tns-android: 2.5.0
Genymotion 2.8.1 image Samsung Galaxy S7 Android 6.0.0

[Please see the screenshot](http://imgur.com/5isyAxu)

**Comment by terreb** [comment]
Same when ran on a real device (tested on Samsung S3, Android 4.4.2).

**Comment by Pip3r4o** [comment]
Please refer to https://github.com/NativeScript/nativescript-vscode-extension/issues/21#issuecomment-281364660
