### ISSUE TITLE
Cannot Debug with "Launch on iOS" with 0.7.0 and NS 3.0.1

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/nativescript-vscode-extension#133]
I built the HelloWorld tutorial for NS3. I installed extension 0.7.0 in VS Code 1.12.1. There are no other extensions installed.

"NativeScript: Run on iOS" works as expected.
Attach on iOS works as expected.
Launch on iOS hangs. I see this output in the debug console:

> [NativeScriptCli] execute: tns --analyticsClient VSCode --version
> [NSDebugAdapter] Using tns CLI v3.0.1 on path 'tns'
> [NSDebugAdapter] Running tns command... 

Then nothing happens, even after 20 minutes of waiting.

The behavior is the same whether or not the emulator is running.

**Comment by Jonatthu** [comment]
This is happening to me to

**Comment by Jonatthu** [comment]
@RobertGardner @pkoleva I test it in a new project and is not working ether, only the attach mode in ios but not launch

**Comment by Jonatthu** [comment]
@RobertGardner My issue has been resolved after I opened XCODE and I've modified my account settings just refreshing, I think something here makes this issue happens now 

https://github.com/NativeScript/nativescript-vscode-extension/commit/a13193e32dba21c07ae13ba095047aae6a3957c4

**Comment by pkoleva** [comment]
Hey, @Jonatthu @RobertGardner,

Thanks for the report, we've reproduced the issue. The "drama" happens when you don't have apple provisioning profiles, which you don't need if you don't deploy on real devices. We'll have a look now and update you when we have progress on it.

**Comment by pkoleva** [comment]
Hey @RobertGardner @Jonatthu, 

Could you try 0.7.2 of the extension. If should fix the issue.

**Comment by Jonatthu** [comment]
@pkoleva It is working thanks! NS Team doing great

**Comment by RobertGardner** [comment]
Yes, 0.7.2 fixed it. Thanks!
