### ISSUE TITLE
tns_modules/fsevents/node_modules/tar-pack/test/fixtures/packed.tar.gz: Error: Duplicate resources

### ISSUE THREAD

**Issue by ishandutta2007** [NativeScript/nativescript-vscode-extension#139]
The following is the stacktrace stacktrace 
```
	at com.android.ide.common.res2.DataSet.checkItems(DataSet.java:466)
	at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:258)
	at com.android.ide.common.res2.AssetSet.loadFromFiles(AssetSet.java:30)
	at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:104)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by Pip3r4o** [comment]
@ishandutta2007 Could you tell us under what circumstances the error occurs? 
What version of NativeScript are you using?
What packages do you have installed (package.json)
What are the steps to reproduce the above?
How is this related to the VSCode Extension?

**Comment by adamauckland** [comment]
I also get this issue when running an Android build, I believe it is because there are two files with the same name but different extensions as part of fsevents fixtures:

platforms/android/src/main/assets/app/tns_modules/fsevents/node_modules/tar-pack/test/fixtures/packed.tar
platforms/android/src/main/assets/app/tns_modules/fsevents/node_modules/tar-pack/test/fixtures/packed.tar.gz

I am currently working around the issue by deleting one of the files during the build.

**Comment by Pip3r4o** [comment]
@adamauckland I am not sure fsevents should be ending up in your prepared files at all.

**Comment by adamauckland** [comment]
Oh, interesting @Pip3r4o. How does tns decide what to copy into `tns_modules`?

**Comment by adamauckland** [comment]
Quick update - this may help someone else, I had `chokidar` and `chokidar-cli` in my `dependencies` list in `package.json` which has a dependency on `fsevents`.

I believe tns-cli copies `devDependencies` into tns_modules` but not `dependencies`, so moving `chokidar` into `devDependencies` has stopped the duplicate resources error.

**Comment by Pip3r4o** [comment]
@adamauckland the NS CLI should only copy all `dependencies` entries in your package json, and their respective production dependencies, and so on, and so on recursively. Everything else that is pinned down as a devDependency will remain as is in the node_modules directory and only be used for the prepare or build process, but not in the final application package.

**Comment by adamauckland** [comment]
Thanks, @Pip3r4o , that makes sense.

**Comment by skopekreep** [comment]
Similar to @adamauckland I had to remove a package from the`dependencies` in my `package.json` file.  In my case it was `nativescript`, which I had upgraded locally for some testing before upgrading globally.  Same result: "Duplicate resources".  Hope this helps save someone some frustration.
