### ISSUE TITLE
Launch for testing

### ISSUE THREAD

**Issue by rmaugusto** [NativeScript/nativescript-vscode-extension#144]
I think run tests with debug in vs code would make tests troubleshoting easier.

Maybe add parameter:
"request": "test"

It should replace debug to test in command line.

**Comment by endarova** [comment]
On very first run of app from Test iOS the command is not executed.
1. tns create app1 --js
2. tns test init
3. Open the app in VSCode and run from Test on iOS
VSCode hangs on: [NSDebugAdapter] Running tns command... and the command is not executed
If you kill the debugger and run Test on iOS again the command is executed

**Comment by endarova** [comment]
Could not load source 'undefined': Could not retrieve content.. when exiting the test method
1. tns create app1 --js
2. tns test init 
3. Open app in VSCode, set breakpoint in tests/example.js file
4. Run from Test on iOS or Android
5. Breakpoint in test is hit. Step over until you exit the test method. You receive Could not load source 'undefined': Could not retrieve content.. message

**Comment by endarova** [comment]
#238
