### ISSUE TITLE
Error "Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by nativescript-ninja** [NativeScript/nativescript-vscode-extension#148]
Getting an error (actually twice, one right after another) as a toast message as soon I try to `Launch on iOS` or `Attach on iOS`.   I can run the project through CLI using `tns run ios` and `tns debug ios --watch` just fine.

**OS**: MacOS 10.13
**NativeScript**:  3.2.1

New machine and no prior version of NativeScript or Visual Studio Code (or this extension) installed.

**Comment by two-bridges** [comment]
Same here

**OS**: MacOS:  10.12.6
**NativeScript**: 3.3.1

**Comment by ivanovit** [comment]
I am closing this issue because the problem should no longer exist in the latest version. 
Please, do not hesitate to reopen it if you continue to experience the issue.
