### ISSUE TITLE
visual studio code not responding with debugger  attached

### ISSUE THREAD

**Issue by somzJosf** [NativeScript/nativescript-vscode-extension#150]
This is happening with both Mac and windows. When I try to attach/ launch on iOs/ android from  VS code using the NativeScript Extension , VS code hangs and not responding intermittently. I have to restart it to make it work again.
![image](https://user-images.githubusercontent.com/8610715/33244508-73fdd67a-d35d-11e7-9b0f-9a397ae04d6a.png)

**Comment by tomasbeke** [comment]
I ran into the same issue on macOS. In my case it was apparently caused by an old breakpoint - the file did not exist anymore in the project. Removing all breakpoints fixed it.

**Comment by ivanovit** [comment]
I am closing this issue because the problem should no longer exist in the latest version. 
Please, do not hesitate to reopen it if you continue to experience the issue.
