### ISSUE TITLE
VSCode debug with NativeScript 4.x.x on Windows not working

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-vscode-extension#166]
The debug experience is creating multiple issues when trying to debug an Angular application on Windows. Using latest VSCode with TypeScript 2.7.2 and NativeScript 4.0.0

Steps to reproduce:
- create a basic Angular app or use [this one](https://github.com/NickIliev/NS-Issues-2018/tree/master/test/debugNGApp)
```
tns create myApp --ng 
```
- set a breakpoint in `item/items.component.ts` on [this line](https://github.com/NickIliev/NS-Issues-2018/blob/master/test/debugNGApp/app/item/items.component.ts#L20)

- hit "Launch on Android" optiin in the debug menu n VSCode

Result:
- the breakpoint is never "hit"
- any changes made in the TypeScript file during debug won't be transpiled to JavaScript (not consistent behavour - sometime this works and sometimes not at all)
- removing the old breakpoins from VSCode is not respected and if we later re-attach and place `debugger;` the VSCode will stoip at non-existing braekpoints.

**_Partial workaround:_**
- use `"stopOnEntry": true` in `vscode/launch.json` to force a breakpoint at the very start of a NativeScript app.
and then use
```
debugger;
```
before a line you would want to debug to force a breakpoint.

**Comment by samuelgonzalez1987** [comment]
This issue happends not only with angular, I am using VSCode with JavaScript and NativeScript. Following your instructions not working for me.
