### ISSUE TITLE
[Feature] GDPR Compliance

### ISSUE THREAD

**Issue by ivanovit** [NativeScript/nativescript-vscode-extension#173]
The analytics must be disabled by default and the user should have the option to accept/decline on extension load. Also, the extension must not track any personal information.

**Comment by ivanovit** [comment]
https://github.com/NativeScript/nativescript-vscode-extension/pull/171

**Comment by ndinev** [comment]
Preparation:
 - You need Fiddler or similar product to monitor network traffic. 
 - After installation [modify ](https://github.com/NativeScript/nativescript-vscode-extension/blob/master/src/analytics/guaService.ts#L12) extension by adding proxy to Fidler in `requestOptions`
 
Test scenario 1 :

- Install VSC extension for the first time(You may need to delete local storage to simulate this)
- In the right lower corner of VSC user should see message with option to tun on or off analytics
- User click 'YES'
- Open preferences/Settings and confirm "nativescript.analytics.enabled": true
- Stop VSC and Execute preparation steps
- Open VSC and execute some nativescript specific command like "Launch on Android"
- Request to google-analytics should appear in Fiddler - inspect it for user sensitive info

Test scenario 2 :

- Install VSC extension for the first time (You may need to delete local storage to simulate this)
- In the right lower corner of VSC user should see message with option to tun on or off analytics
- User click 'NO'
- Open preferences/Settings and confirm "nativescript.analytics.enabled": false
- Stop VSC and Execute preparation steps
- Open VSC and execute some nativescript specific command like "Launch on Android"
- Request to google-analytics should NOT appear in Fiddler

Tested on VSCode 1.23.1
