### ISSUE TITLE
Opening a new VS Code window now displays a NativeScript Extension output pane

### ISSUE THREAD

**Issue by pnb** [NativeScript/nativescript-vscode-extension#176]
Every time I open a new VS Code window, an output pane pops up at the bottom of the window with this text:

    Version: 0.7.4
    Build version: v.2018.5.18.1
    Commit id: bdd68b3156461de296cc6583416c13c9bcb5048f
    NativeScript CLI: 3.4.3

This is not something I've seen before today, though I haven't used this computer since 5/18 when this build was presumably released. It is fairly annoying because I either have to close it or switch to a terminal every time I open a new window, even if it is just a text file or something that has nothing to do with NativeScript. I do not observe any similar behavior in other VS Code installations without the NativeScript extension.

Obviously this is a minor problem in a great extension, but I very frequently open new windows so it is not ideal.

**Comment by ivanovit** [comment]
Fixed. It will be released with next version of  NativeScript Extension.
