### ISSUE TITLE
AAPT2 error

### ISSUE THREAD

**Issue by xjpmauricio** [NativeScript/nativescript-vscode-extension#189]
When trying to launch my app on a real android device, i'm having an error related to aapt during the gradle build. I'm using visual studio code.

This is my debug console output:

[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v4.1.0 on path 'tns'
[NSDebugAdapter] Running tns command...
[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --no-client --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token
Searching for devices...
Preparing project...
Project successfully prepared (Android)
Building project...
Gradle build...

Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:mergeDebugResources'.

> Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Unable to apply changes on device: HSMDU17A28004098. Error is: Command gradlew.bat failed with exit code 1.
[NSDebugAdapter] The tns command finished its execution with code 0.

**Comment by xjpmauricio** [comment]
Ok, solved it by adding this to gradle.properties:
android.enableAapt2=false

Could this issue be related to my user folder having special characters?

**Comment by LeoDupont** [comment]
I set `android.enableAapt2=false` in `gradle.properties` and it now works. But when I launch `./gradlew clean` in my `platforms/android` folder, I get this warning message:

> WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
> Use 'android.enableAapt2=true' to remove this warning.
> It will be removed at the end of 2018..

So what should we do? Is there a way for it to work without using a deprecated, soon-to-be-removed option?

I also have a non-ASCII character in my Windows account name. Unfortunately, this account name cannot be changed and I never get to choose where to install NativeScript requirements or Sidekick...

**Comment by xjpmauricio** [comment]
Hi, I had the same problem with non-ASCII character in my Windows account name and, my solution was to move all android studio related folders, to other folders containing a short path and, with a name containing ASCII characters only. The folders I moved: ANDROID_HOME and GRADLE_USER_HOME.

**Comment by LeoDupont** [comment]
Hello,
Did moving ANDROID_HOME and GRADLE_USER_HOME to a path without special character allowed you to compile without setting `android.enableAapt2=false`?
I just checked my environment variables and the ANDROID_HOME path has no special characters in it (and I don't even have a Gradle-related path).

**Comment by LeoDupont** [comment]
This problem might be solved by upgrading Gradle (source: https://stackoverflow.com/a/46988209).
My `platforms/android/build.gradle` file states I'm using Gradle 3.1.2. and the non-ASCII bug is said to be solved since 3.2.0.

**Comment by xjpmauricio** [comment]
Hi @LeoDupont, It's like you said; the last gradle update totally resolved the need to add "android.enableAapt2=false" in gradle.properties.

**Comment by avinashlb** [comment]
- [ android.enableAapt2=false]
