### ISSUE TITLE
Any way to specify which AVD to use when on Android emulator?

### ISSUE THREAD

**Issue by theremon** [NativeScript/nativescript-vscode-extension#200]
Hi

hitting F5 in VSCode to start debugging (or even with **tns run**), starts the emulator with an image I don't want to actually use (and don't know neither why it's selected nor how to set another 'default').
Is there any way to set the desired AVD in launch.json or any other config file?

Thanks in advance

**Comment by ivanovit** [comment]
Hi,

You can pass extra arguments to the tns CLI using the **tnsArgs** options in your **launch.json**. The **tns run** command has **--device** [parameter](https://docs.nativescript.org/tooling/docs-cli/project/testing/run-android#options) where you can specify which avd to start. 

Example tnsArgs:

```
"tnsArgs": [
	"--device",
	"AVD_Name"
]
```

Also you could start the emulator before debugging. In this case the tns command will use the running emulator without starting a new one.

Please let us know if this solution works for you.

**Comment by ivanovit** [comment]
Closing the issue. If need any further information you could reopen it.
