### ISSUE TITLE
"Launch on iOS" on Windows hangs VS Code and results in never ending debug

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-vscode-extension#217]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - VSCode Extension: 0.8.2

**Describe the bug**
"Launch on iOS" on Windows hangs VS Code and results in never ending debug

**To Reproduce**
1 Create NativeScript project.
2 Add NativeScript launch configuration
3 Go to Debug tab
4 Select "Launch on iOS"
5 Press play button

**Expected behavior**
"Launch on iOS" on Windows should show error and stop the debug operation.

**Comment by ndinev** [comment]
Test Steps
* Start vscode on Windows
* Install latest version - Build version: v.2018.10.19.1 - confirm that it appear in NS console output
* Open project and go to debug view
* Select and execute Launch on iOS
* Verify that there is a vscode notification saying "iOS platform is supported only on OS X"
* Select and execute Attach on iOS
* Confirm that vscode is not froozen
* Verify that there is a vscode notification saying "iOS platform is supported only on OS X"
* Confirm that vscode is not froozen
* Switch to Android and launch it - app should be launched on attached emulator/device

Tested against tns@rc(5.x) and tns@latest(4.2.4)
Build version: v.2018.10.19.1
