### ISSUE TITLE
Debugging not working with --bundle

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-vscode-extension#222]
**Environment**
 - CLI: 5.0.1
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - VSCode: 1.29.1

**To Reproduce**
1) `tns create newApp --js`
2) `cd newApp`
3) `code .`
4) Add `"tnsArgs": ["--bundle"]` in the  `Launch on Android` task.
5) Run the `Launch on Android` task.
6) Set a breakpoint.
7) The breakpoint is grayed out and marked as `unverified` (most probably the bundle js map is not handled properly). 

**Expected behavior**
You should be able to debug the NativeScript apps in VSCode when the `--bundle` or `--hmr` flags are passed.

**Comment by coding-style-review** [comment]
This issue was introduced by the commit from here: https://github.com/NativeScript/nativescript-vscode-extension/issues/213

That commit solves the debug extension issue for the angular template, but adds other issues for the rest of the templates.

**Comment by 18clans** [comment]
Was this ever fixed?  I'm still having this same issue.

**Comment by DimitarTachev** [comment]
@18clans, it was fixed in the new version of the launch.json. If you are using an old project, check your `./.vscode/launch.json` file and delete the `sourceMapPathOverrides`property.

**Comment by xdubx** [comment]
Nop still not working. v.0.9.0

**Comment by DimitarTachev** [comment]
@xdubx Maybe there are some source maps issues in your app (e.g.  the `devtool` property is not configured properly - [here's the proper setup](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.vue.js#L118)).

I suggest you update `nativescript-dev-webpack` to the latest version and execute its update scripts with `./node_modules/.bin/update-ns-webpack --configs` in order to get the latest `webpack.config`.

If this doesn't help, please open a new issue following the issue template in order to allow us investigate it further.

**Comment by xdubx** [comment]
update the webpack config works for me thx for the fast reply.
