### ISSUE TITLE
Getting debug port failed with code: 127

### ISSUE THREAD

**Issue by rgottumu** [NativeScript/nativescript-vscode-extension#23]
When I have more than 1 emulator, Visual Studio Code is not able to launch or attach the debugger. 

if I run `tns run android --device 1` it works fine.

How can I set <Device Id> in launch.json?

**Comment by ivanbuhov** [comment]
Hi @rgottumu 
Open your `launch.json` file located in `.vscode` folder. Under the `Launch on Android Emulator` configuration add property `"tnsArgs": "--device 1"`. The value of `tnsArgs` property is appended to the executed CLI command.
<img width="340" alt="tnsargs" src="https://cloud.githubusercontent.com/assets/2405533/13454729/ac69503e-e061-11e5-850d-4bcd84bcc21a.png">

**Comment by rgottumu** [comment]
Thank you for your response @ivanbuhov This helped a bit but did not solve the problem completely.

My launch.json 
![image](https://cloud.githubusercontent.com/assets/16905130/13476639/9ff1fc2c-e07d-11e5-9c56-7bb714e07475.png)

It correctly identifies the emulator.
Device list: 
![image](https://cloud.githubusercontent.com/assets/16905130/13476607/75e72c5e-e07d-11e5-8486-3dc09b34909d.png)

VS Code:
![image](https://cloud.githubusercontent.com/assets/16905130/13476688/d92c24a4-e07d-11e5-8bfd-95c5404ad1dd.png)

Build finally fails to deploy the application and launch 
`[31;1mCould not find an emulator image to run your project.`

`Command failed: The debug process exited unexpectedly code:127`

**Comment by blagoev** [comment]
Hi it seems you need to use "Launch on Android Device" option. Some emulators are 'reachable' by using that option, especially Visual Studio Android Emulator and Genymotion.

Can you try using Launch on Android Device option?

**Comment by rgottumu** [comment]
@blagoev  You are spot on. I should have tried this when the type is "Device" in the tns device list. 
Thanks a lot for your patience.

**Comment by jgsacris** [comment]
I am running into the same problem when trying to start debugging on a device. My launch.json looks like this:
```
{
			"name": "Launch on Android Device",
			"type": "nativescript",
			"platform": "android",
			"request": "launch",
			"appRoot": ".",
			"sourceMaps": true,
			"diagnosticLogging": false,
			"stopOnEntry": true,
			"emulator": false
		}
```
I am able to launch the device from the command line with tns run --device

Before updating Visual Studio Code to version 0.10.11 and the Extension to v. 0.2.0 it was working OK.

**Comment by blagoev** [comment]
VS code changed the appRoot requirement. Can you switch to ${workspaceRoot} like so

"appRoot": "${workspaceRoot}",

**Comment by mayureshjadhav** [comment]
I am also having the issue and I tried all above things but I am getting following error every time 

Error: error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Only one usage of each socket address (protocol/network address/port) is normally permitted. (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

**Comment by blagoev** [comment]
@mayureshjadhav can you try some of these steps 
http://stackoverflow.com/questions/23415746/how-to-resolve-the-adb-server-didnt-ack-error

**Comment by mayureshjadhav** [comment]
@blagoev Not working for me.

**Comment by mayureshjadhav** [comment]
@blagoev hey, It works now when I restart my computer.

**Comment by tosho** [comment]
`›launch({"name":"Launch on Android Emulator","type":"nativescript","platform":"android","request":"launch","appRoot":"/home/tosho/dev/nativescript/myfish","sourceMaps":true,"diagnosticLogging":true,"emulator":true,"tnsArgs":"--device 1 --log=trace","noDebug":false})
›Getting debug port
Getting debug port
›/bin/sh: 1: tns: not found
/bin/sh: 1: tns: not found
›Command failed: Getting debug port failed with code: 127
Command failed: Getting debug port failed with code: 127
›Error: Getting debug port failed with code: 127
at Object.errP (/home/tosho/.vscode/extensions/Telerik.nativescript-0.2.1/out/webkit/utilities.js:425:13)
at /home/tosho/.vscode/extensions/Telerik.nativescript-0.2.1/out/webkit/webKitDebugAdapter.js:67:26
›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[NativeScript-Debug-Adapter] Getting debug port failed with code: 127"}
›From client: disconnect({"restart":false})
›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}`

**Comment by blagoev** [comment]
@tosho 

> tns: not found

means you don't have {N} CLI configured correctly. What the plugin does is it starts tns command to build the app, start it on the device and then attach to the debugger

check tns command is working for you in bash shell.

**Comment by tosho** [comment]
@blagoev 
`tosho@T440:~/dev/nativescript/sample-Groceries$ npm -g list | grep -i nativescript`
`├─┬ nativescript@2.0.1`
"$ tns run android" works just fine in the terminal. I've tried sample-Groceries, sample-Tasks and the hello-world apps. If I install nativescript in the project folder the error doesn't appear. It might be Visual Studio Code problem I'll try to reinstall it and try again.

**Comment by ivanbuhov** [comment]
@tosho if you are using `nvm` to manage your nodeJS versions, make sure that you have installed the nativescript package globally in your default nodeJS version. To check which is your default node version execute `nvm ls` on the command prompt and you should see in the output something like `default -> 5.5.0 (-> v5.5.0)` If you wish you can change your default nodeJS version by executing `nvm alias default {version}`.

**Comment by tosho** [comment]
it works! I just had to reinstall vscode. thanks

**Comment by gfmoore** [comment]
This is a long time after the issue was posted (Feb 2021 now), but if someone comes here I found that:
```
    {
      "name": "Launch on Android",
      "type": "nativescript",
      "request": "launch",
      "platform": "android",
      "appRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "watch": true,
      "tnsArgs": [
        "--device 1"
      ]
    },
```
worked for me. Note the array [...] for tnsArgs :)
