### ISSUE TITLE
Intellisense like the chrome debuggers

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-vscode-extension#24]
First off, dont even know if this is POSSIBLE :)

In the "old" chrome debuggers, when you type a var name and hit period you'd see a popup intellisense of the available properties...kinda miss this, feel like just typing it in and hitting enter to then open the resulting object adds time.

**Comment by ivanbuhov** [comment]
@sitefinitysteve If you are talking about intellisense in the debugger console
<img width="494" alt="vscode" src="https://cloud.githubusercontent.com/assets/2405533/13773420/cf474d3c-eaa1-11e5-9648-75fc6d1d26e1.png">
we can't do anything about it. This is up to the VS Code team to introduce support for it.
