### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem?).

### ISSUE THREAD

**Issue by fraune** [NativeScript/nativescript-vscode-extension#284]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 6.5.27
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.4
 - Plugin(s): NativeScript Extension for VS Code v0.12.3
 - VSCode: 1.55.1

**Describe the bug**
My team and I test our app by running, `tns run {platform} --no-hmr`. Once the app is running, if we attach the iOS or Android debugger in the VS Code extension, we have trouble with breakpoints. Our breakpoints remain unverified, give the error message listed in the title of this bug, and won't pause execution.

**To Reproduce**
This behavior seemed to begin after a teammate and I updated our Macbooks from macOS Big Sur 11.2.2 to 11.2.3. (Wondering if the Webpack security fix somehow has anything to do with this issue...?)

**Expected behavior**
We should be able to use breakpoints to halt the execution of our code.

**Sample project**
I don't have a sample project/code to share at this time.

**Additional context**
Our project is a NativeScript-Angular-Typescript app for iOS and Android. Running `tns doctor` gives all check marks. Inquire for more specific version info if necessary. We've been able to get the Chrome debugger working, but have found that it's inferior to the VS Code debugger.

My team and I would greatly appreciate some assistance on this. Thanks!

**Comment by fraune** [comment]
**Sample Project/Steps to Reproduce**
I can replicate this behavior with a brand new project.

1. `ns create ns-test-app --ng`
2.  Open VS Code at directory `ns-test-app`
3. Go to the Debug menu, and click the link to `create a launch.json file`, and select the `NativeScript` environment.
4. Run the project (e.g. `ns run android`)
5. In the debugger sidebar of VS Code, click the Play button next to `Attach on Android`
6. Set a breakpoint and see that the breakpoint isn't verified after the debugger is attached

**Comment by jcassidyav** [comment]
For me 
I noticed that the source map had
```{"version":3,"sources":["webpack:///./src/app/di...```

While the launch.json had 
```
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/src/*"
            },
```

So changing the launch.json to 
```
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/*"
            },
```

And debugging started to work.

There is some issue with loading the config still I am getting and error that it is trying to load a pakage.json from 
```
C:\Program Files\Microsoft VS Code\package.json
```

I think 

```
function getProjectRootPath() {
    return process.cwd();
}
```

in @nativescript\webpack\dist\helpers\project.js is returning the vscode cmd path.

but debugging seems to work.

**Comment by jcassidyav** [comment]
This only works when there is no name defined in the package.json as the name ends up in the source map definition and then does not match.

**Comment by jcassidyav** [comment]
I had a look at debugging again today as the chrome debugging wasn't working for me properly ( showing js not ts ).
starting with 
`tns create testD --angular`

Two changes were required to get debugging working in VsCode and chrome.
Add 
`"sourceMap": true,`
 to the tsconfig.json, in the compilerOptions
Add 
            ```
"sourceMapPathOverrides": {
                "webpack://@nativescript/template-hello-world-ng/*": "${workspaceRoot}/*"
            }
```
 to the launch.json for Launch on Android.
`@nativescript/template-hello-world-ng` is the name specified in package.json and this ends up in the source-map
After that I could set breakpoints in item.services.ts / item-detail.component.ts which were hit.

**Comment by fraune** [comment]
@jcassidyav The workaround you provided helped me get breakpoints working for in VS Code on the test app, but not my team's production app. How were you able to inspect the sourcemap? I can't seem to find the file...

**Comment by jcassidyav** [comment]
For me the source maps are at the end of each js file

so I see something like this:

```//# sourceMappingURL=data:application/json;charset=utf-8;base64,askdjlasjdkjas......```

Everything after the base64, is encoded base 64.

Decoding gives a json object where the sources property has entries like:

```"webpack:///<project name>./src/app/module/blank/blank-routing.module.ts"```

The sourcemap generation is controlled by webpack so could be different depending on how it is configured, it can be configured for external source maps for example.

**Comment by fraune** [comment]
Hm, I might be missing something. When I build my app (or the testD example), I can't seem to locate any transpiled js files... is this because they are webpacked? Could you please describe in a little more detail where I can find these files?

**Comment by jcassidyav** [comment]
Sorry I wasn’t very clear. They are in the apk. I don’t have it in front of me. So I can’t remember the exact path.

**Comment by fraune** [comment]
Thanks! I have successfully achieved your workaround! I'll recap my steps in case it can help anyone else...

After unarchiving the built apk **and its contents** until I saw a folder, I found the file you mentioned at: `platforms/android/app/build/outputs/apk/debug/app-debug.apk 2 2/assets/app/bundle.js`.

I inspected the bundle.js file, and most of the way down I found the line starting with this: `//# sourceMappingURL=data:application/json;charset=utf-8;base64,`. I converted the first few lines of the subsequent base64 and found:
```json
{"version":3,"sources":["webpack:///../$_lazy_route_resource lazy namespace object","webpack:///../node_modules/moment/locale sync ^\\.\\/.*$","webpack:///./app.component.html","webpack:///./app.component.ts","webpack:///./app.css","webpack:///./app.module.ts", ...
```
My team's project structure is slightly different from yours and the sample project, plus I don't have my app's name set in my package.json. So, I slightly modified the code you added to your launch.json, and placed it into each of my launch/attach configurations. Here's what worked for my project:
```json
"sourceMapPathOverrides": {
    "webpack:///*": "${workspaceRoot}/app/*"
}
```

Launching and attaching on iOS/Android now works for me. Breakpoints getting hit again! I'm not sure if this will be a permanent fix, but it got my team and I off the ground again! Thanks, @jcassidyav.

**Comment by fraune** [comment]
One possible issue that still exists with my configuration is that when setting breakpoints, I now get an error from VS Code in my debug console:

`Error processing "breakpointLocations": 'Debugger.getPossibleBreakpoints' was not found: [object Object]`

Hasn't seemed to affect my ability to actually hit the breakpoints though... any thoughts on this?

**Comment by Marcel0001** [comment]
Tried everything above still doesn't work.

Tried launching and attaching debugger using the nativescript plugin in vscode.

launch.json

`{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach on Android",
      "type": "nativescript",
      "request": "attach",
      "platform": "android",
      "appRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "watch": false
    },
    {
      "name": "Launch on Android",
      "type": "nativescript",
      "request": "launch",
      "platform": "android",
      "appRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "watch": true,
      "sourceMapPathOverrides": {
        "webpack://<myprojectname>/*": "${workspaceRoot}/*"
      }
    }
  ]
}`

**Comment by Danny168** [comment]
I am also getting the same error message: Error when trying to require webpack.config.js file from path 'E:\appname\webpack.config.js'. Error is: Error: Cannot find module 'C:\Users\username\AppData\Local\Programs\Microsoft VS Code\package.json'.

I've changed my launch.json file to be 
        {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",           
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:// appname/*": "${workspaceRoot}/*",
            },
            "watch": true
        },

My webpack.config.js is the default as created:
const webpack = require("@nativescript/webpack");

module.exports = (env) => {
	webpack.init(env);

	// Learn how to customize:
	// https://docs.nativescript.org/webpack

	return webpack.resolveConfig();
};

**Comment by darkyelox** [comment]
Same problem here with NativeScript v8, it's a shame this wonderful framework lacks of good tools and some of them very outdated.

DEBUG CONSOLE OUTPUT:

Error when trying to require webpack.config.js file from path '/Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/webpack.config.js'. Error is: Error: Cannot find module '/package.json'
Require stack:
- /Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/node_modules/@nativescript/webpack/dist/helpers/project.js
- /Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/node_modules/@nativescript/webpack/dist/helpers/dependencies.js
- /Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/node_modules/@nativescript/webpack/dist/helpers/externalConfigs.js
- /Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/node_modules/@nativescript/webpack/dist/index.js
- /Users/diego/Documents/development/mobile/bridge/NativeScript/acr-app/webpack.config.js
- /Users/diego/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebugAdapter.js
- /Users/diego/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebug.js
- /[eval]

**Comment by ebewley** [comment]
I am using {N} v8.1.4 and {A} v12.2.0 and in addition to the debugger not stopping on breakpoints, I was also getting the message that of @darkyelox in which it was looking for a file at C:\Program Files\Microsoft VS Code\package.json.  None of the other suggestions worked, so I thought to add an almost empty _package.json_ file at the location specified.  That worked!  The errors went away and debugging started working.  By an almost empty _package.json_ file, I mean...
```
{
}
```
I hope this helps some of you!

**Comment by NathanWalker** [comment]
We'll move to this discussion where answer is provided: https://github.com/NativeScript/NativeScript/discussions/9693

**Comment by aqweeva** [comment]
Might be a bit late here to the party, but this article Finally Resolved the issue for me!!!  (after fighting with this for 2 days)
Pretty much the common solution worked.
1. Added to tsconfig.json
"sourceMap": true,

2. Added to my launch.json
            "sourceMapPathOverrides": {
                "webpack://@nativescript/appnameinmy.package.json/*": "${workspaceRoot}/*"
            }
            
           Thank you!
