### ISSUE TITLE
[VSCode 0.10.10] Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#29]
Moved from https://github.com/NativeScript/nativescript-vscode-extension/issues/25#issuecomment-194971919

**Comment by ivanbuhov** [comment]
@cime is this reproducible with the v0.2.0?

**Comment by ivanbuhov** [comment]
ping donangel

**Comment by ivanbuhov** [comment]
ping @donangel

**Comment by donangel** [comment]
Well verify later tonight and will ping back.

**Comment by donangel** [comment]
Seems to run OK, at least the scenarios I changed are fine.

**Comment by ivanbuhov** [comment]
Thanks @donangel
