### ISSUE TITLE
Command A Interferes With Select All

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-vscode-extension#31]
On Mac, having Cmd + A mapped to Android build interferes with the OS default of Cmd + A being "Select All". This seems like a pretty essential piece of functionality to override.

**Comment by ivanbuhov** [comment]
Hi @burkeholland,
We agree with this and we [already changed](https://github.com/NativeScript/nativescript-vscode-extension/issues/18) the key mappings for the `run on android` command to `Cmd+Alt+A`. This will be in production very soon.

**Comment by calebeaires** [comment]
:+1:

**Comment by ivanbuhov** [comment]
v0.2.0 is live so I am closing the issue
