### ISSUE TITLE
Getting debug port failed with code 127

### ISSUE THREAD

**Issue by Daxito** [NativeScript/nativescript-vscode-extension#33]
Version V0.2.0 now gives this error, android and ios gives the same error code 127

![screen shot 2016-03-14 at 11 02 56 am](https://cloud.githubusercontent.com/assets/16787057/13750751/cf124c0e-e9d4-11e5-9f59-956792e04d94.png)

**Comment by ivanbuhov** [comment]
@Daxito the highlighted version is the version of the `launch.json` file format which coincides with the extension version. You can check the extension version by executing "Extensions: Show Installed Extensions".
<img width="611" alt="vscode-extension-version" src="https://cloud.githubusercontent.com/assets/2405533/13751347/65199954-ea12-11e5-9907-2e07bab7a900.png">
Delete your `launch.json` file and generate it again. For the purpose of the test you can create a brand new application. Make sure that you have no other emulators running while launching the debugger. 
Can you provide the log in the debugger console for both iOS and Android?

**Comment by Daxito** [comment]
ok, I had the correct version, but after reinstalling it it now seems ok 50%, I am not able to debug using the ios emulator but i can debug with an android device, iOS keeps saying this:

Unable to stop session. Result is: 3892314142

And it never opens the app.
Thanks!

**Comment by Daxito** [comment]
And I can also confirm that I get the same error code 127 (Command failed: The debug process exited unexpectedly code:127) when launching an ios real device, again, launching android real device is ok.

Thanks

**Comment by ivanbuhov** [comment]
@Daxito It seems that this is a [known issue in the NativeScript CLI](https://github.com/NativeScript/nativescript-cli/issues/1328#issuecomment-185587921). If you confirm that the same happens when running `tns debug ios --emulator` from the command line, too, I will close the issue.

**Comment by Daxito** [comment]
Yes confirmed, you can close it.
Thanks!
