### ISSUE TITLE
Unable to debug app on Android emulator

### ISSUE THREAD

**Issue by JohanBeumer** [NativeScript/nativescript-vscode-extension#38]
With Visual studio code I'm trying to debug a Nativescript app on an Android emulator. When I start the debug (F5) it takes about 1 minute to install the app on the emulator. Then it starts running the app. A white screen pops up, pops down and pops up again. This takes about 20 seconds to finish by saying in the console "NativeScript Debugger did not start in time".

What should I do to be able to debug my app on an Android emulator?

**Comment by blagoev** [comment]
There are some timeouts when debugging an app. The message that you see means emulator is very slow on your machine. In that case one way to workaround that is by starting the application on the emulator and then trying to attach to it. You may use the tns command

tns debug android --debug-brk --no-client

and then after the app is started it will wait for a debugger to connect. Then try to attach to it through VS Code.
Also make sure you have an emulator instance running before trying to debug.

We may increase the debug start timeout a bit to accommodate for slow starting emulators.

**Comment by JohanBeumer** [comment]
Indeed the Android emulator is very, very slow. In a message on google plus I came across the tip to debug my NativeScript app on the Visual Studio Android Emulator. It's way faster and debugging through Visual studio code works like a charm. So I will use that.

Thnx for your response!

**Comment by blagoev** [comment]
Yep VS Emulator or  Genymotion Emulator are faster than the stock ones. Make sure you use "Launch/Attach on Device" cause these emulators present themselves as devices
