### ISSUE TITLE
Perform save of all files before deploying to android/iOS

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-vscode-extension#40]
Coming from a VS environment I keep finding myself in a situation that I made changes to couple of files and directly issuing a deploy command, only to notice that this does not save the files :) Would be good (if the vscode APIs allow) to perform a save of all project files before performing the actual deploy command.

**Comment by Daxito** [comment]
+1 
Happens to me a million times!

**Comment by ivanbuhov** [comment]
Hi guys,
Currently, VS Code supports autosaving of files. You can learn more [here](https://code.visualstudio.com/docs/editor/codebasics#_saveauto-save). Please, share if this solution is working for you.

**Comment by PeterStaev** [comment]
@ivanbuhov  I've just put `"files.autoSave": "onFocusChange"` in my user settings and it works like a charm! Thanks!
