### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by Daxito** [NativeScript/nativescript-vscode-extension#48]
I get this error when trying to run the App using the Emulator, any ideas?
Thank you!

BUILD SUCCESSFUL
Total time: 47.467 secs
Project successfully built.
Using c:\App\platforms\android\build\outputs\apk\APK-debug.apk
Error: connect ECONNREFUSED 127.0.0.1:5554
at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
Sending exception report (press Ctrl+C to stop)...
Command failed: The debug process exited unexpectedly code:0
Closing debug connection

**Comment by blagoev** [comment]
Can you enable verbose logging in your launch.json file in "Launch on Android Emulator"
Find this line : 
> "diagnosticLogging": false

and set it to true.

**Comment by Daxito** [comment]
@blagoev 

at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
›Sending exception report (press Ctrl+C to stop)...
Sending exception report (press Ctrl+C to stop)...
›Command failed: The debug process exited unexpectedly code:0
Command failed: The debug process exited unexpectedly code:0
›Closing debug connection
Closing debug connection
›Error: The debug process exited unexpectedly code:0
at Object.errP (C:\Users\ali\.vscode\extensions\Telerik.nativescript-0.2.1\out\webkit\utilities.js:425:13)
at C:\Users\ali\.vscode\extensions\Telerik.nativescript-0.2.1\out\webkit\webKitDebugAdapter.js:67:26
at process._tickCallback (internal/process/next_tick.js:103:7)
›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"[NativeScript-Debug-Adapter] The debug process exited unexpectedly code:0"}
›From client: disconnect({"restart":false})
›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}

**Comment by blagoev** [comment]
Ok, this is not very different and usually it means the debug process is not listening on the device side.

Can you verify you are using the latest NativeScript version also try updating this project android platform by

> tns platform remove android
> tns platform add android

Also you can try debugging via the command line by 

> tns debug android

this will launch the dev tools in a browser and will show that a debugging is possible outside vscode
