### ISSUE TITLE
Invoke debugger without --debug-brk

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#53]
Remove the `--debug-brk` flag passed to the CLI when using launch configuration. This requires changing the CLI because currently the VS Code extension relies on the CLI to [print a magical message](https://github.com/NativeScript/nativescript-cli/blob/9a8891f46d6304dd0cc16ef2cde0d7af455c91b2/lib/services/android-debug-service.ts#L220) on launching on Android. This printing is happening only when the `--debug-brk` is passed. The CLI should be changed to print the message when no `--debug-brk` flag is passed, too.

**Comment by pkoleva** [comment]
In Extension 0.7.0 no longer passing --debug-brk
