### ISSUE TITLE
npm hints in the extension are not correct

### ISSUE THREAD

**Issue by bundyo** [NativeScript/nativescript-vscode-extension#60]
The stated **npm install -g nativescript** is not really correct - the option should be before **install** or npm will assume that you want to install a package with name **-g**

https://github.com/NativeScript/nativescript-vscode-extension/blob/5173e273c5f498371e09893dcae7776fa75a4bb5/src/services/NsCliService.ts#L61

Same goes for the **gulp** option in **CONTRIBUTING.md**

**Comment by blagoev** [comment]
fixed
