### ISSUE TITLE
Launching on Android builds two times

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#61]
Launching on Android builds the application two times in a row.

Maybe `tns debug android --get-debug-port` triggers application build. @blagoev

**Comment by NicoleZA** [comment]
I have the same problem too

**Comment by blagoev** [comment]
Already fixed here. Closing this 10x

**Comment by NicoleZA** [comment]
I have tested this and it is still compiling twice
