### ISSUE TITLE
Launching on Android builds two times #61

### ISSUE THREAD

**Issue by NicoleZA** [NativeScript/nativescript-vscode-extension#62]
I have tested issue #61 and it is still compiling 2 on version 0.3.0

**Comment by blagoev** [comment]
@NicoleZA 

It is a fix in {N} CLI which is not published yet. It is in master branch. 
The VSCode extension simply calls 

"tns debug android --get-debug-port"

this command is building the project which is not needed. If you need this urgently you may hotfix this on your side by  finding the file android-debug-service.js and locate this function in there debugOnDevice

then change the code to do be like this

https://github.com/NativeScript/nativescript-cli/commit/84cada9b5263286a4a4064851971cdfb55104190

The android-debug-service.js file is part of {N} installation somewhere globally on your machine where your current global node_modules are installed.

Cheers,
blagoev

**Comment by NicoleZA** [comment]
Thanks you
