### ISSUE TITLE
Support LiveSync Debugging

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-vscode-extension#70]
The NativeScript CLI now supports LiveSync debugging through `tns debug ios|android --watch`, however, that same functionality does not appear to be available through Visual Studio Code. As soon as I perform one LiveSync the debugger no longer works as expected.

**Comment by blagoev** [comment]
thanks, @tjvantoll.

We have plans on making this happen in VSCode but it requires some synced dancing between vscode + debug adapter + client app that will take time. 

Right now you can rely on the fast Sync option to manually push the changes to your app directly from within VSCode. (without starting livesync on a console window). This will push only the changed file and will restart the app with debugger attached.

**Comment by blagoev** [comment]
This option should be available when you add a new launch.json to your project. Make sure you recreate this file on existing projects.

**Comment by tjvantoll** [comment]
Hey @blagoev,

I see the new “Sync” options, but I’m confused about what the workflow is supposed to be. When I run “Sync” the debugger starts as expected, but it does not setup a watcher. So if I want to see my changes I have to go to a terminal and run `livesync` manually, which kills the debugger.

**Comment by blagoev** [comment]
the workflow is manually clicking that option when you make a change. It is equivalent of running livesync (w/o watch) + debug from a console.

The idea is that the user knows when to do a sync run or debug run. Sync does not rebuild so if you change a AndroidManifest.xml for example you need full debug run (which will do rebuild) and Sync is only for js/xml/css or other changes that do not require rebuild/repackage.

**Comment by tjvantoll** [comment]
@blagoev Ok thanks, that does make sense. Is the plan to change the Sync open to also watch so that the manual step is no longer necessary?

**Comment by blagoev** [comment]
yep I believe it is

**Comment by ivanbuhov** [comment]
I am closing this in favour of https://github.com/NativeScript/nativescript-vscode-extension/issues/78
