### ISSUE TITLE
Sync on Android option does not work on devices

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-vscode-extension#77]
1. Open a project in VSCode and generate configurations
2. Start Sync on Android
   Expected result: App is synced and hits initial break point
   Actual result: App is synced but the following error appears `Command failed: Can't connect. Check the application is running on the device`

CLI version 2.3.0
VSCode 1.5.0

**Comment by denkomanceski** [comment]
+1

**Comment by TeddyBo** [comment]
+1

**Comment by hshristov** [comment]
This happens on device (tested on Android 6.0).
