### ISSUE TITLE
Support for Sync with watch

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-vscode-extension#78]

**Comment by born2net** [comment]
this is awesome if we can get it fixed!

**Comment by born2net** [comment]
NativeScript is awesome but still needs A **LOT** of improvements when it comes to the development experience in Windows environment... lots of hangs and hick-ups

**Comment by ivanbuhov** [comment]
Enabled with https://github.com/NativeScript/nativescript-vscode-extension/pull/96
