### ISSUE TITLE
tns-core-modules 2.3.0 doesn't show styles inside of ListView

### ISSUE THREAD

**Issue by ownleviathan** [NativeScript/nativescript-vscode-extension#81]
Hello
When I updated the last version, all my css styles inside of ListView disappeared. If a downgrade to version 2.1.0 it works.

**Comment by ivanbuhov** [comment]
@ownleviathan Can you be more specific on this? If I understand you correctly you have applied custom CSS styling to a ListView instance and after updating tns-core-modules to v2.3.0 your css style is not applied? Am I right?

**Comment by ownleviathan** [comment]
yes, that correct

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/NativeScript#2790
