### ISSUE TITLE
NVM PATH Issue on Startup with tns/nativescript shell-command

### ISSUE THREAD

**Issue by flexxis** [NativeScript/nativescript-vscode-extension#83]
Hi,

recently i have installed nativescript extension for vs code and i get the following error on startup:

![image](https://cloud.githubusercontent.com/assets/16099458/18831726/a77afd1e-83e7-11e6-82f4-15b7629fedf9.png)

Node is installed via NVM.  I had already installed nativescript via `npm install -g nativescript` (and did it again to make it sure), so it is available at
`~/.nvm/versions/node/v5.10.1/lib/node_modules/nativescript`.
 If I print my current environment in the vs code terminal , it also looks well and i am able to execute tns / nativescript command.

printenv:
> NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/home/user/.nvm/versions/node/v5.10.1/lib/node_modules 

When launching the debug session with attach to android, the tns command can also not be found.

![image](https://cloud.githubusercontent.com/assets/16099458/18831926/d7bfc666-83e8-11e6-95d9-258ba188ef39.png)

launch.json:
`     {
            "name": "Attach on Android",
            "type": "nativescript",
            "platform": "android",
            "request": "attach",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "diagnosticLogging": false,
            "emulator": false
        }`

Visual Studio Code is installed as deb package with sudo (/usr/bin/code). It seems to have the wrong path environment variable and i cannot quite figure out why.

What could be the solution to make the tns path known to vs code at startup?

Thanks in advance

**Comment by ivanbuhov** [comment]
@flexxis Make sure you have installed the nativescript package in your default node version. For more detailed info check the [Install NativeScript](https://github.com/NativeScript/nativescript-vscode-extension#install-nativescript) section in the Readme.

**Comment by flexxis** [comment]
@ivanbuhov default node environment is set (` nvm alias default stable`). but this did not the trick.

I think the cause is that vs code was installed with sudo, so it searches in the global PATH environment when executing tns in the shell. nvm adjusts only the home PATH. 
The integrated terminal of vscode seems to run with user PATH, a bit misleading.

After executing vscode locally in home dir (and not install it as root), it works now. If vscode does not support command line path arguments e.g. for tns/nativescript, that should be the only workaround

**Comment by ivanbuhov** [comment]
@flexxis Please verify that `nvm alias default stable` does not changes your node version only for the current shell session by opening a new terminal window and checking the node version there.
FYI: the master branch version of the extension has an optional [`nativescriptCliPath` option](https://github.com/NativeScript/nativescript-vscode-extension/commit/ee0e5e67fa1ac12d85a4c22795b6df3bfc2bf403) which can be set in your `launch.json` file.

**Comment by flexxis** [comment]
@ivanbuhov thanks for your quick help and the source changes !

Finally i have found the solution: Apparently nativescript installer had created a .tnsrc and a .bash_profile file in my linux home path with following code snippet : 
```
###-tns-completion-start-###
if [ -f ~/.tnsrc ]; then 
    source ~/.tnsrc 
fi
###-tns-completion-end-###
```

The problem is if you have had no .bash_profile file before (as on my ubuntu OS), the .profile file will be neglected by linux as you log in. In my case .profile had the path initializiation code for node etc., so the window manager / graphically executed programs had no PATH reference.

For anyone who has the same problem: Append 
`if [ -r ~/.profile ]; then . ~/.profile; fi`
in .bash_profile to source the file.

However, it would be great for future if the installer would be smart enough to recognize if there is no file.
