### ISSUE TITLE
VSCode watch for changes

### ISSUE THREAD

**Issue by sant123** [NativeScript/nativescript-vscode-extension#85]
Hi, I would like to know if there's any change to implement livesync changes to VSCode? Currently I'm using Sync and Launch on Android, but I have to restart the app for every change I make.

Thank you!

**Comment by ivanbuhov** [comment]
@sant123 Currently, the VSCode debugger doesn't reattach itself on every sync of the app. It is something we will support in the future. You can follow the progress here: https://github.com/NativeScript/nativescript-vscode-extension/issues/78.

**Comment by ivanbuhov** [comment]
Duplicate of https://github.com/NativeScript/nativescript-vscode-extension/issues/78
