### ISSUE TITLE
Initial checks of VSCode Extension show error if cli is not isnatlled globally even when local cli path is specified

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-vscode-extension#87]
We already have a way to use local installation of CLI in a  specific project, but we throw an error if a global CLI is not present on start of VS Code.

User scenarios that should be considered:
1. I want to use a local installation of CLI , that's why in my project's launch.json I set up nativescriptCliPath property - why should I get error, that I don't have a global installation, when I specified I will use the local instalation?
2. I open VS Code without a specific project and I do not intend to create NS project - why should I get that error message?
3. I open VS Code with a NS project, but I still don't have launch.json file - why should I get that error message when I haven't said which CLI I'll use?

**Comment by ivanbuhov** [comment]
Update (for v0.5.0 and above):
The CLI path can be set in `./vscode/settings.json` like this:
```
{
    "nativescript.tnsPath": "/path/to/tns"
}
```
If the option is not set, the default value is `tns` which means that the CLI will be searched globally.

**Comment by renestalder** [comment]
This sometimes work, sometimes it doesn't.

I have this in my settings.json:

```
"nativescript.tnsPath": "node_modules/.bin/tns"
```

And I'm sure this once worked for me in the insider version of Visual Studio Code, but currently it doesn't.

I always get:
```
[NativeScriptCli] execute: node_modules/.bin/tns --analyticsClient VSCode --version
Error: Command failed: node_modules/.bin/tns --analyticsClient VSCode --version
zsh:1: no such file or directory: node_modules/.bin/tns

Error: NativeScript CLI not found. Use 'nativescript.tnsPath' workspace setting to explicitly set the absolute path to the NativeScript CLI.
```
