### ISSUE TITLE
Launch/Sync on iOS fails because no teamId is specified

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-vscode-extension#93]
Prerequisites: 
Xcode 8

Error in console:
Xcode 8 requires a team id to be specified when building for device.
You can specify the team id by setting the DEVELOPMENT_TEAM setting in build.xcconfig file located in App_Resources folder of your app, or by using the --teamId option when calling run, debug or livesync commnads.

Workarround 1:
Add TeamID in  App_Resources/iOS/build.xcconfig -> DEVELOPMENT_TEAM 

Workarround 2:
Add "tnsArgs": "--teamId  TeamID" in launch.json Launch on iOS and Sync on iOS options

**Comment by yyosifov** [comment]
@pkoleva Here's what I saw, when tested now with tns @ 2.5.4:

<details>
Building project...

Xcode 8 requires a team id to be specified when building for device.
You can specify the team id by setting the DEVELOPMENT_TEAM setting in build.xcconfig file located in App_Resources folder of your app, or by using the --teamId option when calling run, debug or livesync commnads.

Found and using the following development team installed on your system: Yosif Yosifov (xxxxxx)

Build settings from command line:
    ARCHS = armv7
</details>

And the App built & ran successfully on the device.

**Comment by pkoleva** [comment]
The problem appears when you have more than one team on your machine

**Comment by SamuelGRwebfab** [comment]
I have removed all extra teams from xcode, specified the team id# in the build.xcconfig file, AND i have used the --teamId option. Still throws the same error. Any ideas?

**Comment by yyosifov** [comment]
@SamuelGRwebfab Where did you make changes? Here are the steps I've tried.

If you want to set the teamId in the build.xcconfig:

- Open app/App_Resources/iOS/build.xcconfig
- And add `DEVELOPMENT_TEAM = 8TxxxxxxxF;`

If you want to pass it as `tnsArgs` in the vscode configuration:

- Open .vscode/launch.json
- Add to the `"name": "Launch on iOS"` configuration the `tnsArgs` option with your teamId:
  `"tnsArgs": "--teamId 8TxxxxxxxF"`

Let me know if these 2 ways work for you? 

If it still doesn't work, can you please share your `tns --version`, `node --version`, 'vscode version', `NativeScript Extension version` and some part of your configuration files? (xcconfig/launch.json)

Best,
Yosif

**Comment by SamuelGRwebfab** [comment]
@yyosifov I should have updated my post. I managed to get past this error by removing all traces of my certs, and then just putting them back, 3 times. This completely resolved my signing issue however now I have another, but this new issue is unrelated to this post.

**Comment by yyosifov** [comment]
@SamuelGRwebfab Sorry for your troublers. Glad to hear it's working for you now!

I've created a PR which opens a Quick Pick selector whenever you have multiple Teams, therefore I hope we won't have this issue in the near future.

**Comment by SamuelGRwebfab** [comment]
@yyosifov I wouldnt say its working but i dont have signing issues now! That sounds great tho!
